# Generated by Django 3.2.5 on 2024-12-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
    ]
