# Generated by Django 5.1.1 on 2025-05-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_transaction_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempurchase',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itempurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itempurchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
